Add escalation to XSS using script gadgets
dwisiswant0/ppfuzz pull request #16
Opened 2021-07-14 19:44 UTC by dwisiswant0

## Proposed of Changes
- See #15 15

2021-07-14 20:32 UTC, mattsse requested changes
executing async call now in the main stream loop will definitely degrade performance because this blocks until the call has completed.
There are ways around this:
* move this also into the check function directly if possible
* spawn these jobs (evaluate + close) with `async_task` and put them in a vec to await after the loop (futures_join)
* use a state machine model, this will require more work and a lot of refactoring but is definitely the more elegant solution and will also make it easier to add additional evaluation tasks. A state machine pattern is very common, in fact the `async` code compiles itself to state machines, but more complex since you usually need to implement `Future` directly, which means no `.await` but `poll`.
So for this entire fuzzer use case you can rewrite this by introducing your own `FuzzerStream` (or something) that implements `Stream` directly. This could look like

```rust

enum Evaluation {
    FingerPrint(Pin<Box<dyn Future< Output = ()>>>),
    // .. other types of evaluations, that makes it easy to potentially chain different evaluations:
   TryThisFirst(Pin<Box<dyn Future< Output = (Page, bool)>>>),
   ThenTryThisIfOk(Pin<Box<dyn Future<..>>>)
}

// same thing as within the current check function
type CheckFuture = Pin<Box<dyn Future< Output = Result<(Url, Page, is_err), (Url, ..., detail)>>>;

pub struct Fuzzer {
    // this would be the thing that `buffered_unordered()` returns
    checks: FuturesUnordered<CheckFuture>,
   // this are the additional evaluations that you would like to execute based on output of the `CheckFuture`s
    evaluation: Vec<Evaluation>,
}

impl Stream for Fuzzer {
  type Output = ... // here you could add some diagonstics type or if nothing should be returned for each check result you can implement Future directly

fn poll_next(
    self: Pin<&mut Self>,
    cx: &mut Context<'_>
) -> Poll<Option<Self::Item>> {
   // here comes the difficult part that will require you to learn how poll + Pin works 
https://rust-lang.github.io/async-book/04_pinning/01_chapter.html 
}


}
```

2021-07-14 20:32 UTC, mattsse commented on src/fuzzer.rs
> +						.await
If you're awaiting here this will block until the page is evaluated, meaning all the pending scans aren't polled in the meantime

2021-07-14 20:32 UTC, mattsse commented on src/fuzzer.rs
> +				p.close().await.unwrap();
same thing, this blocks until the page is actually closed and prevents progress on the scans.

2021-07-14 20:42 UTC, dwisiswant0 commented on src/fuzzer.rs
> +fn show_pontential(url: &str, gadget: &str) {
It says `cannot be formatted with the default formatter`.

2021-07-14 20:45 UTC, mattsse commented on src/fuzzer.rs
> +fn show_pontential(url: &str, gadget: &str) {
ah, forgot to suggest that you then need to call `.as_ref()` und url:

```suggestion
println!("[{}] {} {}", "INFO".blue(), url.as_ref(), gad.green());
```

2021-07-15 05:21 UTC, dwisiswant0 commented
Just add checks if target has been escalated & remove additional query payloads from builder. If you don't mind, please review again, @mattsse.

2021-07-15 08:15 UTC, mattsse approved these changes
LGTM!

2021-07-15 08:15 UTC, mattsse commented on src/fuzzer.rs
> +				}
this is fine, but I think you probably can also use something like `target.query_pairs().into_iter().filter(|q| payloads.iter().all(|p|q.0 !=p) )`

2021-07-15 14:18 UTC, dwisiswant0 commented
Thanks for the review, @mattsse! I'll definitely learn the suggestion of the 3rd way you suggest.

2021-07-15 14:18 UTC, merged